parameters:
    'dealroadshow_proximity.proxy_classes_dir': '%env(DEALROADSHOW_PROXIMITY_PROXY_CLASSES_DIR)%'
    'dealroadshow_proximity.proxy_namespace': '%env(DEALROADSHOW_PROXIMITY_PROXY_NAMESPACE)%'
    'env(DEALROADSHOW_PROXIMITY_PROXY_CLASSES_DIR)': '%kernel.project_dir%/var/proxy'
    'env(DEALROADSHOW_PROXIMITY_PROXY_NAMESPACE)': 'Dealroadshow\Proximity\Proxy'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Dealroadshow\Proximity\ProxyGenerator:
        arguments:
            $proxyClassesNamespace: '%dealroadshow_proximity.proxy_namespace%'
    Dealroadshow\Proximity\ProxyFactory:
        arguments:
            $proxyClassesDirectory: '%dealroadshow_proximity.proxy_classes_dir%'
